services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: CSUBotDB
      POSTGRES_USER: CSUBotDB_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: