services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: CSUBotDB
      POSTGRES_USER: CSUBotDB_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U CSUBotDB_user -d CSUBotDB"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  api:
    build: ./API/CSUBotAPI
    restart: always
    ports:
      - "5000:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=CSUBotDB
      - POSTGRES_USER=CSUBotDB_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_CONNECTION_STRING=redis:6379
      - REDIS_PASSWORD=
      - BOT_API_KEY=${BOT_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./API/CSUBotAPI/DbScripts:/app/DbScripts 
    

volumes:
  pgdata:
  redisdata: